import path from 'path'
import HtmlWebpackPlugin from 'html-webpack-plugin'
import MiniCssExtractPlugin from 'mini-css-extract-plugin'
import webpack from 'webpack'

const isProduction = process.env.NODE_ENV == 'production'

const config: webpack.Configuration = {
  entry: './src/index.tsx',
  output: {
    path: path.resolve(__dirname, '..', 'server', 'src', 'main', 'resources', 'ui'),
    publicPath: '/',
    clean: true,
    filename: '[name].[contenthash].js',
    chunkFilename: '[name].[contenthash].js'
  },
  devtool: isProduction ? 'source-map' : 'inline-source-map',
  optimization: {
    chunkIds: 'total-size',
    removeAvailableModules: true,
    usedExports: true,
    splitChunks: {
      chunks: 'all',
      minSize: 100000,
      maxSize: 500000,
      minRemainingSize: 0,
      minChunks: 1,
      cacheGroups: {
        defaultVendors: {
          test: /[\\/]node_modules[\\/]/,
          priority: -10,
          reuseExistingChunk: true
        },
        default: {
          minChunks: 2,
          priority: -20,
          reuseExistingChunk: true
        }
      }
    }
  },
  performance: {
    hints: false
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'index.ejs',
      templateParameters: {
        serverUrl: isProduction ? '' : 'http://localhost:9000'
      },
      inject: 'body'
    }),
    new MiniCssExtractPlugin()
  ],
  module: {
    rules: [
      {
        test: /\.tsx?$/i,
        loader: 'ts-loader',
        exclude: ['/node_modules/']
      },
      {
        test: /\.s?css$/i,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: '@teamsupercell/typings-for-css-modules-loader',
            options: {
              banner:
                '// autogenerated by typings-for-css-modules-loader. \n// Please do not change this file!',
              formatter: 'prettier'
            }
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              esModule: true,
              modules: {
                localIdentName: isProduction ? '[hash:base64]' : '[path]-[name]-[local]'
              }
            }
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true
            }
          }
        ]
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2|png|jpg|gif)$/i,
        type: 'asset'
      }

      // Add your rules for custom modules here
      // Learn more about loaders from https://webpack.js.org/loaders/
    ]
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.jsx', '.js', '...']
  }
}

const configCreator = () => ({
  ...config,
  mode: isProduction ? 'production' : 'development'
})

export default configCreator
