version = 3.11.0    // mandatory
runner.dialect = scala3    // mandatory, see below for available dialects

maxColumn = 120
align.preset = most
newlines {
  beforeCurlyLambdaParams = multilineWithCaseOnly
  selectChains {
    enclose = true
    classicCanStartWithoutApply = true
    classicKeepFirst = true
  }
}  
indent {
  main = 2
  callSite = 2
  defnSite = 2
}

rewrite {
  scala3 {
    convertToNewSyntax = false
  }

  rules = [Imports, PreferCurlyFors, SortModifiers]
  sortModifiers.preset = styleGuide
  imports = {
    selectors = fold
    sort = scalastyle
    removeRedundantSelectors = true
    
    groups = [
      ["org\\.pi\\.farm\\..*"],
      ["doobie\\..*", "io\\.scalaland\\..*"],
      ["zio\\..*"],
      ["java\\..*", "scala\\..*"]
    ]
    contiguousGroups = "no"
  }

  trailingCommas.style = "never"
}
