; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
monitor_speed = 115200
framework = arduino
lib_deps = 
	beegee-tokyo/DHT sensor library for ESPx@^1.19
	bblanchon/ArduinoJson@^7.2.2
build_flags = 
    -DSERIAL_SPEED=115200
    -DCORE_DEBUG_LEVEL=3
    -DUDP_PORT=9090
    -DCONTROLLER_ID=2
extra_scripts = pre:scripts/wifi_credentials.py
