base-folder = "./data"

database.url = "jdbc:h2:"${base-folder}"/db/pi-farm;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"

udp-server {
  port = 9090
  port = ${?UDP_PORT}
  ip = "0.0.0.0"
  ip = ${?UDP_IP}
  queue-size = 16
  num-threads = 2
  num-threads = ${?UDP_NUM_THREADS}
}

http-server {
  port = 9000
  port = ${?HTTP_PORT}
  address = "0.0.0.0"
  address = ${?HTTP_ADDRESS}
  num-threads = 4
  num-threads = ${?HTTP_NUM_THREADS}
}

static-service {
  base-dir = ${base-folder}"/static/"
}