base-folder = "./data"

database.url = "jdbc:h2:"${base-folder}"/db/pi-farm;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"

udp-server {
  port = 9090
  port = ${?UDP_PORT}
  ip = "localhost"
  queue-size = 16
}

http-server {
  port = 9000
  port = ${?HTTP_PORT}
}

static-service {
  base-dir = ${base-folder}"/static/"
}