ALTER TABLE periphery_types ADD COLUMN type VARCHAR(255) NOT NULL DEFAULT 'Float';

ALTER TABLE configurations ADD COLUMN name TEXT NOT NULL;
ALTER TABLE configurations ADD COLUMN description TEXT NOT NULL;
