database {
  driver = "org.h2.Driver"
  url = "jdbc:h2:./data/pi-farm;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
  user = "sa"
  password = ""
  pool {
    minimum-idle = 5
    maximum-pool-size = 20
    idle-timeout = 300000
    max-lifetime = 1200000
    connection-timeout = 30000
  }
}
